[package]
name = "notmirrox/pretty-react-hooks"
description = "A collection of useful hooks for React"
version = "0.1.1"
license = "MIT"
authors = ["mirrox", "littensy"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = [
    "rokit.toml",
    "selene.toml",
    "selene_definitions.yaml",
    "stylua.toml",
    "test.project.json",
    "testez-companion.toml",
    "**/*.spec.luau",
    "src/utils/testez.luau",
]

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
React = "jsdotlua/react@^17.2.1"
Promise = "howmanysmall/typed-promise@^4.0.6"

[dev-dependencies]
ReactRoblox = "jsdotlua/react-roblox@^17.2.1"
TestEZ = "roblox/testez@0.4.1"